<doc>
<s>
C'	1	ce	CL	CLS	mwehead=ADV|mwelemma=c'est_pourquoi|n=s|p=3|s=suj|sentid=Europar.550_00126	5	mod	_	_	_	_
est	2	être	V	V	component=y|m=ind|n=s|p=3|t=pst	1	dep_cpd	_	_	_	_
pourquoi	3	pourquoi	ADV	ADV	component=y	1	dep_cpd	_	_	_	_
j'	4	il	CL	CLS	n=s|p=1|s=suj	5	suj	_	_	LVC:head	il_de
attends	5	attendre	V	V	m=ind|n=s|p=1|t=pst	0	root	_	_	_	_
de	6	de	P	P	_	5	de_obj	_	_	LVC:child	il_de
tout	7	tout	A	ADJ	g=m|n=s|s=ind	9	mod	_	_	_	_
le	8	le	D	DET	g=m|n=s|s=def	9	det	_	_	_	_
monde	9	monde	N	NC	g=m|n=s|s=c	6	obj.p	_	_	_	_
,	10	,	PONCT	PONCT	s=w	9	ponct	_	_	_	_
Albanais	11	albanais	N	NC	g=m|n=p|s=c	9	mod	_	_	_	_
et	12	et	C	CC	s=c	11	coord	_	_	_	_
Serbes	13	serbe	N	NC	g=m|n=p|s=c	12	dep.coord	_	_	_	_
,	14	,	PONCT	PONCT	s=w	5	ponct	_	_	_	_
qu'	15	que	C	CS	s=s	5	obj	_	_	_	_
ils	16	il	CL	CLS	g=m|n=p|p=3|s=suj	17	suj	_	_	_	_
laissent	17	laisser	V	V	m=ind|n=p|p=3|t=pst	15	obj.cpl	_	_	_	_
les	18	le	D	DET	n=p|s=def	19	det	_	_	_	_
troupes	19	troupe	N	NC	g=f|n=p|s=c	17	obj	_	_	_	_
de	20	de	P	P	_	19	dep	_	_	_	_
la	21	le	D	DET	g=f|n=s|s=def	22	det	_	_	_	_
KFOR	22	KFOR	N	NPP	s=p	20	obj.p	_	_	_	_
en	23	en	P	P	_	17	ato	_	_	_	_
paix	24	paix	N	NC	g=f|n=s|s=c	23	obj.p	_	_	_	_
.	25	.	PONCT	PONCT	s=s	5	ponct	_	_	_	_
</s>
<s>
J'	1	il	CL	CLS	n=s|p=1|s=suj|sentid=Europar.550_00127	2	suj	_	_	_	_
approuve	2	approuver	V	V	m=ind|n=s|p=1|t=pst	0	root	_	_	ID:head	approuver_monsieur
ce	3	ce	PRO	PRO	_	2	obj	_	_	_	_
qu'	4	que	PRO	PROREL	s=rel	6	obj	_	_	_	_
a	5	avoir	V	V	m=ind|n=s|p=3|t=pst	6	aux.tps	_	_	_	_
dit	6	dire	V	VPP	g=m|m=part|n=s|t=past	3	mod.rel	_	_	_	_
M.	7	monsieur	N	NC	g=m|n=s|s=c	6	suj	_	_	ID:child;VPC:head	approuver_monsieur;monsieur_le
Sakellariou	8	Sakellariou	N	NPP	s=p	7	mod	_	_	_	_
:	9	:	PONCT	PONCT	s=w	2	ponct	_	_	_	_
la	10	le	D	DET	g=f|n=s|s=def	11	det	_	_	VPC:child	monsieur_le
communauté	11	communauté	N	NC	g=f|n=s|s=c	13	suj	_	_	_	_
internationale	12	international	A	ADJ	g=f|n=s|s=qual	11	mod	_	_	_	_
doit	13	devoir	V	V	m=ind|n=s|p=3|t=pst	2	mod	_	_	_	_
envoyer	14	envoyer	V	VINF	m=inf	13	obj	_	_	_	_
les	15	le	D	DET	n=p|s=def	16	det	_	_	_	_
forces	16	force	N	NC	g=f|n=p|s=c	14	obj	_	_	_	_
de	17	de	P	P	_	16	dep	_	_	_	_
police	18	police	N	NC	g=f|n=s|s=c	17	obj.p	_	_	_	_
qu'	19	que	PRO	PROREL	s=rel	22	obj	_	_	_	_
elles	20	il	CL	CLS	g=f|n=p|p=3|s=suj	22	suj	_	_	_	_
a	21	avoir	V	V	m=ind|n=s|p=3|t=pst	22	aux.tps	_	_	_	_
promises	22	promettre	V	VPP	g=f|m=part|n=p|t=past	16	mod.rel	_	_	_	_
.	23	.	PONCT	PONCT	s=s	2	ponct	_	_	_	_
</s>
<s>
Nous	1	il	CL	CLS	n=p|p=1|s=suj|sentid=Europar.550_00191	2	suj	_	_	_	_
voulons	2	vouloir	V	V	m=ind|n=p|p=1|t=pst	0	root	_	_	_	_
protéger	3	protéger	V	VINF	m=inf	2	obj	_	_	_	_
notre	4	son	D	DET	n=s|s=poss	5	det	_	_	_	_
droit	5	droit	N	NC	g=m|n=s|s=c	3	obj	_	_	_	_
à	6	à	P	P	_	5	dep	_	_	_	_
avoir	7	avoir	V	VINF	m=inf	6	obj.p	_	_	LVC:head;LVC:head;LVC:head	avoir_idée;avoir_sentiment;avoir_émotion
des	8	un	D	DET	n=p|s=ind	9	det	_	_	_	_
idées	9	idée	N	NC	g=f|n=p|s=c	7	obj	_	_	LVC:child	avoir_idée
,	10	,	PONCT	PONCT	s=w	7	ponct	_	_	_	_
des	11	un	D	DET	n=p|s=ind	12	det	_	_	_	_
sentiments	12	sentiment	N	NC	g=m|n=p|s=c	7	obj	_	_	LVC:child	avoir_sentiment
,	13	,	PONCT	PONCT	s=w	7	ponct	_	_	_	_
des	14	un	D	DET	n=p|s=ind	15	det	_	_	_	_
émotions	15	émotion	N	NC	g=f|n=p|s=c	7	obj	_	_	LVC:child	avoir_émotion
,	16	,	PONCT	PONCT	s=w	7	ponct	_	_	_	_
contre	17	contre	P	P	_	7	mod	_	_	_	_
l'	18	le	D	DET	n=s|s=def	19	det	_	_	_	_
invasion	19	invasion	N	NC	g=f|n=s|s=c	17	obj.p	_	_	_	_
technologique	20	technologique	A	ADJ	n=s|s=qual	19	mod	_	_	_	_
des	21-22	_	_	_	_	_	_	_	_	_	_
de	21	de	P	P	_	19	dep	_	_	_	_
les	22	le	D	DET	g=m|n=p|s=def	24	det	_	_	_	_
grands	23	grand	A	ADJ	g=m|n=p|s=qual	24	mod	_	_	_	_
frères	24	frère	N	NC	g=m|n=p|s=c	21	obj.p	_	_	_	_
,	25	,	PONCT	PONCT	s=w	2	ponct	_	_	_	_
comme	26	comme	C	CS	s=s	2	mod	_	_	_	_
nous	27	le/lui	CL	CLO	n=p|p=1|s=obj	29	a_obj	_	_	_	_
le	28	le	CL	CLO	g=m|n=s|p=3|s=obj	29	obj	_	_	_	_
laisse	29	laisser	V	V	m=ind|n=s|p=3|t=pst	26	obj.cpl	_	_	ID:head	laisser_à_penser
à	30	à	P	P	_	29	a_obj	_	_	ID:child	laisser_à_penser
penser	31	penser	V	VINF	m=inf	30	obj.p	_	_	ID:child	laisser_à_penser
le	32	le	D	DET	g=m|n=s|s=def	33	det	_	_	_	_
cas	33	cas	N	NC	g=m|s=c	29	suj	_	_	_	_
récent	34	récent	A	ADJ	g=m|n=s|s=qual	33	mod	_	_	_	_
d'	35	de	P	P	_	33	dep	_	_	_	_
Échelon	36	Échelon	N	NPP	s=p	35	obj.p	_	_	_	_
,	37	,	PONCT	PONCT	s=w	33	ponct	_	_	_	_
sur	38	sur	P	P	_	43	p_obj	_	_	_	_
lequel	39	lequel	PRO	PROREL	g=m|n=s|s=rel	38	obj.p	_	_	_	_
cette	40	ce	D	DET	g=f|n=s|s=dem	41	det	_	_	_	_
Assemblée	41	assemblée	N	NC	g=f|n=s|s=c	43	suj	_	_	_	_
se	42	le/lui	CL	CLR	p=3|s=refl	43	aff	_	_	IReflV:head	le/lui_pencher
penchera	43	pencher	V	V	m=ind|n=s|p=3|t=fut	33	mod.rel	_	_	IReflV:child	le/lui_pencher
sous	44	sous	P	P	_	43	mod	_	_	_	_
peu	45	peu	ADV	ADV	_	44	obj.p	_	_	_	_
.	46	.	PONCT	PONCT	s=s	2	ponct	_	_	_	_
</s>
</doc>